### ISSUE TITLE
ChatGPT 国内可使用镜像汇总

### ISSUE THREAD

**Issue by yzfly** [yzfly/awesome-chatgpt-zh#1]
分享几个可以直接在国内打开访问的ChatGPT网站：

https://theb.ai/
http://newb.site/
http://a.aizh.app/
https://qachat.cn/
https://freegpt.one/
https://chat.muspimerol.site/
https://chat2.xeasy.me/
https://dev.yqcloud.top/
https://chat.forchange.cn/
https://chater.lanyun1103.top/
https://94gpt.com/
https://askai.ws/
https://chat.51buygpt.com/
http://v.ourwechat.com/chatgpt.html
https://fastgpt.app/
https://chat.ninvfeng.xyz/

**Comment by clayboby** [comment]
补一个，微信直接登录PC两用支持GPT4的。https://www.vivi-chat.com/#/chat 公众号貌似最近有活动

**Comment by yzfly** [comment]
国内服务不稳定，本人时间精力有限，镜像站停止维护
