### ISSUE TITLE
大佬，openai官网下的国内注册链接噶了

### ISSUE THREAD

**Issue by Gavintofd** [yzfly/awesome-chatgpt-zh#15]
![image](https://user-images.githubusercontent.com/88378639/233940557-ff59ccf3-8383-463e-b2b6-b6c0e0943f25.png)
大佬，这个飞书的文档好像噶了，无法访问

**Comment by lpstart** [comment]
又不行了，封的也太快了

**Comment by yzfly** [comment]
> 又不行了，封的也太快了

用这个吧，新的： https://yunyinghui.feishu.cn/wiki/CrWxwkrWIiWawQkUCKXc4cuPnpe
