### ISSUE TITLE
ChatGPT 国内镜像站——欢迎在此发布可用镜像站

### ISSUE THREAD

**Issue by yzfly** [yzfly/awesome-chatgpt-zh#3]
最新chatgpt镜像站，访问比较麻烦的可以使用如下下
可用 免费 免登录 免KEY 部分速度快

https://theb.ai/
https://chatgpt-plus.app/  稳定、免费 不限次数
https://ctrl.opengpt88.com/    需登录 稳定、免费 不限次数 自愿赞赏
https://www.vivi-chat.com/#/chat   支持GPT4，微信一键登录直接使用，送次数，公众号送天卡
 https://index.chat.bnu120.space/   免费免登免翻墙，无限次数，沉浸式对话，多线路可选，勤更新
http://www.msai.fun/ 无需登录 不限次数 自愿赞赏
http://aizh.app/ 登录使用，有限使用次数
https://qachat.cn/
https://freegpt.one/
https://chat2.xeasy.me/
https://dev.yqcloud.top/
https://chat.forchange.cn/
https://chater.lanyun1103.top/
https://94gpt.com/
https://askai.ws/
https://chat.51buygpt.com/
http://v.ourwechat.com/chatgpt.html
https://fastgpt.app/
https://chat.ninvfeng.xyz/

**Comment by caipeizhi** [comment]
http://175.178.88.119/ 这个也是

**Comment by yzfly** [comment]
看很多都是用的[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) 部署的，使用原版作者的 demo 站点也ok 
 https://chat-gpt-next-web.vercel.app/

**Comment by CNSeniorious000** [comment]
可以加入我创建的一个国内可用的免费ChatGPT镜像站吗

[chat.muspimerol.site](https://chat.muspimerol.site/)

**Comment by yzfly** [comment]
> 可以加入我创建的一个国内可用的免费ChatGPT镜像站吗
> 
> [chat.muspimerol.site](https://chat.muspimerol.site/)

可以发在这里，你也知道国内的镜像站网址很不稳定

**Comment by 740400019** [comment]
收录提交：ChatGPT中文

网址
http://a.aizh.app/

网站类型
ChatGPT站点

是否需要国际网络
否

ico 路径
https://camo.githubusercontent.com/ca54604e6873602da61c4dedda5c4f58a4c7453a22b61fb7655c75e7408efbf4/68747470733a2f2f73742e616935352e63632f66617669636f6e2f7971636c6f75642e746f702e737667

使用方式
登录使用，有限使用次数

**Comment by yzfly** [comment]
> 

已收录到 issues 第一条 comment

**Comment by yzfly** [comment]
> 可以加入我创建的一个国内可用的免费ChatGPT镜像站吗
> 
> [chat.muspimerol.site](https://chat.muspimerol.site/)

已收录到第一条 comment

**Comment by lmyprogrammer** [comment]
您好，可以辛苦您收录下我的网站吗

网站标题：MSAI-有趣的魔术AI
网址：http://www.msai.fun

无需登录 不限次数 自愿赞赏

**Comment by yzfly** [comment]
> 您好，可以辛苦您收录下我的网站吗
> 
> 网站标题：MSAI-有趣的魔术AI 网址：http://www.msai.fun
> 
> 无需登录 不限次数 自愿赞赏

已收录到第一条 comment

**Comment by CNSeniorious000** [comment]
> > 可以加入我创建的一个国内可用的免费ChatGPT镜像站吗
> > [chat.muspimerol.site](https://chat.muspimerol.site/)
> 
> 已收录到第一条 comment

你好，我的这个域名被墙了，现在新域名是 [chat0.muspimerol.site](https://chat0.muspimerol.site/) 原域名也已配置重定向到新域名，请问能更新一下吗 谢谢

（目前本站也是 无需登录 不限次数 自愿赞赏）

**Comment by yzfly** [comment]
> > > 可以加入我创建的一个国内可用的免费ChatGPT镜像站吗
> > > [chat.muspimerol.site](https://chat.muspimerol.site/)
> > 
> > 
> > 已收录到第一条 comment
> 
> 你好，我的这个域名被墙了，现在新域名是 [chat0.muspimerol.site](https://chat0.muspimerol.site/) 原域名也已配置重定向到新域名，请问能更新一下吗 谢谢
> 
> （目前本站也是 无需登录 不限次数 自愿赞赏）

已更新

**Comment by clayboby** [comment]
您好，可以辛苦您收录下我的网站吗
网页标题：VIVI-Chat
支持GPT4，微信一键登录直接使用，送的次数也够。公众号还送天卡
https://www.vivi-chat.com/#/chat 
准备长期稳定搞的，是要做api平台（后端用quarkus+jdk17，后续会接入其他公司所有ai接口），非常感谢🙏

**Comment by yzfly** [comment]
> 您好，可以辛苦您收录下我的网站吗 网页标题：VIVI-Chat 支持GPT4，微信一键登录直接使用，送的次数也够。公众号还送天卡 https://www.vivi-chat.com/#/chat 准备长期稳定搞的，是要做api平台（后端用quarkus+jdk17，后续会接入其他公司所有ai接口），非常感谢🙏

已收录到第一条 comment

**Comment by 740400019** [comment]
> 收录提交：ChatGPT中文
> 
> 网址 http://aizh.app/
> 
> 网站类型 ChatGPT站点
> 
> 是否需要国际网络 否
> 
> ico路 [https://camo.githubusercontent.com/ca54604e6873602da61c4dedda5c4f58a4c7453a22b61fb7655c75e7408efbf4/68747470733a2f2f73742e616935352e63632f666169c76663 f75642e746f702e737667](https://camo.githubusercontent.com/ca54604e6873602da61c4dedda5c4f58a4c7453a22b61fb7655c75e7408efbf4/68747470733a2f2f73742e616935352e63632f66617669636f6e2f7971636c6f75642e746f702e737667)
> 
> 使用方式 登录使用，有限使用次数

网址更新了：http://aizh.app/

**Comment by CNSeniorious000** [comment]
> https://chat0.muspimerol.site 无需登录 不限次数 自愿赞赏

很抱歉又麻烦你们！但是上面这个域名又被墙了。**不过我们改了架构，现在已经一周没有新域名被墙了。**

另一方面，我开了多条线路，并建立了自己一个小索引页面 <https://index.chat.bnu120.space/>，希望引流到这上面。在这上面我会更新我的新线路（如果旧线路被墙的话），就不用再麻烦你们了~

另外希望能将本站那一行的广告词改成 “免费免登免翻墙，无限次数，沉浸式对话，多线路可选，勤更新” 行吗，谢谢🙏

**Comment by knight-666** [comment]
您好，可以辛苦您收录下我的网站吗


网址：https://gpt.opengpt88.com

需登录 稳定、免费 不限次数 自愿赞赏

**Comment by yzfly** [comment]
> > https://chat0.muspimerol.site 无需登录 不限次数 自愿赞赏
> 
> 很抱歉又麻烦你们！但是上面这个域名又被墙了。**不过我们改了架构，现在已经一周没有新域名被墙了。**
> 
> 另一方面，我开了多条线路，并建立了自己一个小索引页面 https://index.chat.bnu120.space/，希望引流到这上面。在这上面我会更新我的新线路（如果旧线路被墙的话），就不用再麻烦你们了~
> 
> 另外希望能将本站那一行的广告词改成 “免费免登免翻墙，无限次数，沉浸式对话，多线路可选，勤更新” 行吗，谢谢🙏

已更新

**Comment by yzfly** [comment]
> 您好，可以辛苦您收录下我的网站吗
> 
> 网址：https://gpt.opengpt88.com
> 
> 需登录 稳定、免费 不限次数 自愿赞赏

已收录

**Comment by knight-666** [comment]
> > 您好，可以辛苦您收录下我的网站吗
> > 网址：https://gpt.opengpt88.com
> > 需登录 稳定、免费 不限次数 自愿赞赏
> 
> 已收录

地址变更 https://ai.opengpt88.com/

**Comment by yzfly** [comment]
> > > 您好，可以辛苦您收录下我的网站吗
> > > 网址：https://gpt.opengpt88.com
> > > 需登录 稳定、免费 不限次数 自愿赞赏
> > 
> > 
> > 已收录
> 
> 地址变更 https://ctrl.opengpt88.com/

已更新

**Comment by clayboby** [comment]
> 您好，可以辛苦您收录下我的网站吗 网页标题：VIVI-Chat 支持GPT4，微信一键登录直接使用，送的次数也够。公众号还送天卡 https://www.vivi-chat.com/#/chat 准备长期稳定搞的，是要做api平台（后端用quarkus+jdk17，后续会接入其他公司所有ai接口），非常感谢🙏

地址变更，请去帮忙更新，谢谢：
https://chat.zhenbs.com/

微信登录后，每天都免费用，注册就送GPT4试用。也可游客体验
每邀请一个人增加一次GPT4的使用次数，外加送GPT3五次和余额赠送
公众号还有各种福利，实现3.5和4的使用

**Comment by clayboby** [comment]
> > 您好，可以辛苦您收录下我的网站吗 网页标题：VIVI-Chat 支持GPT4，微信一键登录直接使用，送的次数也够。公众号还送天卡 https://www.vivi-chat.com/#/chat 准备长期稳定搞的，是要做api平台（后端用quarkus+jdk17，后续会接入其他公司所有ai接口），非常感谢🙏
> 
> 地址变更，请去帮忙更新，谢谢： https://chat.zhenbs.com/
> 
> 微信登录后，每天都免费用，注册就送GPT4试用。也可游客体验 每邀请一个人增加一次GPT4的使用次数，外加送GPT3五次和余额赠送 公众号还有各种福利，实现3.5和4的使用

忘了加上GPT4兑换码：TRYGPT4

**Comment by ansen666** [comment]
ChatGPT国内手机版
https://ai004.com/

**Comment by zhpd** [comment]
@yzfly 
您好，可以辛苦您收录下我的网站吗
网址：https://chatgpt-plus.app/
稳定、免费 不限次数

**Comment by yzfly** [comment]
> @yzfly 您好，可以辛苦您收录下我的网站吗 网址：https://chatgpt-plus.app/ 稳定、免费 不限次数

已收录

**Comment by Aomferni** [comment]
您好，我们这边的网站可以收录一下吗？
域名：https://www.zaiwen.top/
网站这边已经备案，承诺只要能支撑，做现有服务永久免费，
目前支持模型：GPT3.5 、GPT4(由于额度即将告罄，目前已全面放开限制，直到2023.6.22)、chatglm-130b（清华官方API）、
其他功能：简单SD模型、简单PDF/txt解析与对话、会话分享链接上传、会话分组
目前还在稳定更新中，详情可以查看使用说明书：https://hk4llw3wld.feishu.cn/docx/AvFGd6KX8o8U7QxjY63c0jBGnlT

**Comment by CNSeniorious000** [comment]
你好🙏🏻可以麻烦把 #1 中的 [chat.muspimerol.site](https://chat.muspimerol.site) 和 #3 中的 [index.chat.bnu120.space](https://index.chat.bnu120.space) 都换成 [free-chat.asia](https://ic.free-chat.asia) 吗

因为前天我这两个域名备案被吊销了，域名解析直接用不了了，甚至都没法配置重定向到新域名😭

**Comment by yzfly** [comment]
国内服务不稳定，本人时间精力有限，镜像站停止维护

**Comment by yemao221** [comment]
2024年最稳定梯子VPN，科学上网2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
[![QQ20240730 - 132944](https://github.com/user-attachments/assets/d537a5f3-3ec8-4d71-b979-99a01ea8a3c9)](https://www.xxxlsop.com/#/register?code=sf9UTRC0)
