### ISSUE TITLE
神奇海螺

### ISSUE THREAD

**Issue by hankexu** [yzfly/awesome-chatgpt-zh#5]
### 你有什么问题吗？何不来问问神奇的海螺呢？
![image](https://user-images.githubusercontent.com/2455540/228590698-4e4fbdcc-b4ca-4f56-bbc6-a4296ce7e7c5.png)

* 《神奇海螺》目前主要的功能有两大块，一块是对话，一块是技能。  
![qrcode](https://user-images.githubusercontent.com/2455540/228584292-6b41cc01-810c-4a1a-a22a-9785884c6396.jpeg)

    *  在神奇海螺的朋友们选择一个角色，可以开启对话，每个角色我都预设了prompts，定义了一些性格特征，回答问题的范围，同时也加了很多内容限制，避免它触及敏感话题，为了节省token，每轮会话目前限制在15回合，会话压缩功能正在开发中。  
 <img src="https://user-images.githubusercontent.com/2455540/228581853-c860472d-0da1-45c2-b3ef-efcbfcc0fcf4.png" width="400"><img src="https://user-images.githubusercontent.com/2455540/228581951-e6ce596b-9a0c-4fd8-9ca3-a4b7e3bd117c.png" width="400">
   * 技能则是任务更明确，一问一答的模式，定义了设定更加精细的prompts，对用户输入也有更加明确的提示。  
   <img src="https://user-images.githubusercontent.com/2455540/228582120-967d833d-118b-4ca2-a548-c0e7f598c9e2.png" width="400"><img src="https://user-images.githubusercontent.com/2455540/228582220-e0a9a8a5-86be-47e5-9855-b615fe5be954.png" width="400">
*《神奇海螺》目前上线了抖音和微信平台， 使用技能或者对话，都会消耗积分，注册，签到，邀请注册都能获得积分，暂时没有广告，积分充值功能目前只在抖音上开通了。看到很多朋友的小程序已经被下架了，不知道我的能存活多久，还有一些想法正在落实中，希望能在下架之前和大家见面。

**Comment by yzfly** [comment]
已收录到小程序板块
